# -------- BUILD STAGE --------
# Contains Go compiler + build tools
FROM golang:1.24-alpine AS builder

WORKDIR /app

# Needed for downloading modules
RUN apk add --no-cache git

# Copy dependency files first for Docker cache
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the source code
COPY . .

# Compile Go code into a single static binary
# CGO_ENABLED=0 → no C deps
# GOOS=linux → target Linux
# GOARCH=amd64 → target x86_64 servers
# ./cmd → folder with main.go
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -o auth ./cmd


# -------- RUNTIME STAGE --------
# Minimal Linux image (no Go installed)
FROM alpine:3.19

WORKDIR /app

# Required for HTTPS calls to other services
RUN apk add --no-cache ca-certificates

# Copy ONLY the compiled binary from builder
COPY --from=builder /app/auth ./auth

# Gateway listens on 9001
EXPOSE 9001

# Configurable port (ECS / compose friendly)
ENV PORT=9001

# Start the container
ENTRYPOINT ["./auth"]
